name: comic_vine_app
description: "A Flutter-based mobile application that consumes the Comic Vine REST API to display the latest comics and detailed issue information. The app uses Flutter Bloc for state management and follows clean architecture practices."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.6
  go_router: ^14.2.0
  intl: any
  get_it: ^7.2.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  generate: true
  assets:
    - assets/mock_data/comics.json
  uses-material-design: true